---
- name: Install PHP and PHP-FPM
  apt:
    name:
      - php7.4
      - php7.4-fpm
      - php7.4-mysql
      - php7.4-xml
      - php7.4-mbstring
    state: present
    update_cache: yes

- name: Ensure PHP-FPM is running
  service:
    name: php7.4-fpm
    state: started
    enabled: yes
