- name: Copy Laravel Nginx configuration
  template:
    src: laravel_nginx.conf.j2
    dest: /etc/nginx/sites-available/laravel
  notify: restart nginx

- name: Enable Laravel site
  file:
    src: /etc/nginx/sites-available/laravel
    dest: /etc/nginx/sites-enabled/laravel
    state: link
  notify: restart nginx

- name: Remove default Nginx site symlink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
